name: r2d2
channels:
  - huggingface
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - numpy=1.26.0
  - pandas=2.1.1
  - scipy=1.11.3
  - scikit-learn=1.3.1
  - matplotlib=3.8.0
  - attrs=23.1.0
  - tqdm=4.66.1
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - transformers=4.33.3
  - hydra-core=1.3.2
  - pyarrow=13.0.0
  - requests=2.31.0
  - cattrs=23.1.2
  - tiktoken=0.5.1
  - pqdm=0.2.0
  - sentence-transformers=2.2.2
  - sql-metadata=2.6.0
  - sqlglot=18.5.1